name: Vue.js CI

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때만 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.2.0'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to gh-pages branch
      run: |
        # GitHub 계정 정보 설정
        git config --global user.name "yc13033"
        git config --global user.email "yc13033@studymax.kr"

        # 병합 방식을 명시적으로 설정 (merge 방식 사용)
        git config pull.rebase false
        
        # 원격의 gh-pages 브랜치 가져오기
        git pull origin gh-pages
        
        # 현재 브랜치의 dist 폴더를 gh-pages 브랜치에 force push
        git add -f dist
        git commit -m "Deploy to gh-pages"
        
        # gh-pages 브랜치 체크아웃 및 dist 폴더 강제 푸시
        git subtree push --prefix dist origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub Actions의 자동 인증을 위한 토큰